import = ["~/dotfiles/alacritty/.config/alacritty/alacritty.toml"]

# Linux Specific Keybindings
[[keyboard.bindings]]
key = "C"
mods = "Alt"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
action = "Paste"
